language: node_js

node_js:
  - "stable"

cache:
  directories:
    - "node_modules"
  
script: 
  - npm test
  - npm run coverage

services:
- mysql

before_script:
- mysql -e 'CREATE DATABASE IF NOT EXISTS spreeDB;'
- mysql -u root spreeDB < server/database/tshirtshop.sql