export default {
  createNew: table => `INSERT INTO ${table} set ?`,
  getById: (table, id) => `Select * from ${table} where ${id} = ?`,
  getByEmail: table => `Select * from ${table} where email = ?`,
  getAll: table => `Select * from ${table}`,
  getAllAndSort: (table, sortBy, order) => `Select * from ${table} ORDER BY ${sortBy} ${order}`,
  getAllByValue: (table, value) => `Select * from ${table} where ${value} = ?`,
  updateById: table => `UPDATE ${table} SET ? WHERE id = ? `,
  updateByEmail: table => `UPDATE ${table} SET ? WHERE email = ? `,
  deleteById: table => `DELETE FROM ${table} where id = ?`,
  getProductAttributesProcedure: 'CALL catalog_get_product_attributes(?)',
  getOrderDetailsProcedure: 'CALL orders_get_order_details(?)',
  getBriefOrderDetailsProcedure: 'CALL orders_get_order_short_details(?)',
  getCustomerOrdersProcedure: 'CALL orders_get_by_customer_id(?)',
  getDepartmentProcedure: 'CALL catalog_get_department_details(?)',
  getAllDepartmentsProcedure: 'CALL catalog_get_departments()',
  getDepartmentCategoriesProcedure: 'CALL catalog_get_department_categories(?)',
  getProductCategoriesProcedure: 'CALL catalog_get_categories_for_product(?)',
  createOrderProcedure: 'CALL shopping_cart_create_order(?,?,?,?)',
  createCustomerProcedure: 'CALL customer_add(?,?,?)',
  getCustomerByEmailProcedure: 'CALL customer_get_login_info(?)',
  getCustomerByIdProcedure: 'CALL customer_get_customer(?)',
  updateCustomerProcedure: 'CALL customer_update_account(?,?,?,?,?,?,?)',
  updateCustomerCreditCardProcedure: 'CALL customer_update_credit_card(?,?)',
  updateCustomerAddressProcedure: 'CALL customer_update_address(?,?,?,?,?,?,?,?)'
};
