version: 2
jobs:
 build:
  docker:
   - image: circleci/node:latest
   - image: circleci/mysql:latest
        environment: 
          MYSQL_DATABASE: cXBmCDuY1h
          MYSQL_USER: cXBmCDuY1h
          MYSQL_PASSWORD: aupZ5y6BnH
   
  working_directory: ~/turingbackend

  steps:
   - checkout
   - sudo apt install -y mysql-client

   - restore_cache:
      keys:
       - v1-dependencies-{{ checksum "package.json" }}
       - v1-dependencies-

   - run: npm install

   - save_cache:
      paths:
       - node_modules
      key: v1-dependencies-{{ checksum "package.json" }}
   
   - run:
      name: Wait for DB
      command: dockerize -wait tcp://127.0.0.1:3306 -timeout 120s
   
   - run:
      name: Database migration
      command: mysql -u cXBmCDuY1h -p aupZ5y6BnH -h 127.0.0.1 cXBmCDuY1h < server/database/tshirtshop.sql

   - run: npm test
   - run: npm run coverage